stages:
  - audit
  - build
image:                             rust:latest

variables:
  GIT_STRATEGY:                    fetch
  GIT_SUBMODULE_STRATEGY:          recursive
  CI_SERVER_NAME:                  "GitLab CI"
  CARGO_HOME:                      "/ci-cache/${CI_PROJECT_NAME}/cargo/${CI_JOB_NAME}"
  CARGO_TARGET:                    x86_64-unknown-linux-gnu
  REGISTRY:                        registry.parity.io/parity/infrastructure/scripts

cargo_audit:
  stage:                           audit
  script:
    - cargo audit
  tags:
    - linux-docker
  allow_failure:                   true
  
cargo_remote_build:
  stage:                           build
  script:
    - cargo build --release
  tags:
    - linux-docker
